/*
    22/11/2022
    11:12 p.m.
 */
package Vista;

import Clases.Producto;
import Controlador.GestionProductos;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author Juan Jose Marin
 */
public class VentaZapatos extends javax.swing.JFrame {

    //Variables para uso
    int CantidadDeProductos = 0;
    GestionProductos gestionProductos = new GestionProductos();

    public VentaZapatos() {
        initComponents();
        setLocationRelativeTo(this);//Esto es para decirle que el frame se abra en el centro de la pantalla
        ImagenesComponentes();
        MensajeLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TPpestanas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnNike = new javax.swing.JButton();
        lblLogoNike = new javax.swing.JLabel();
        lblLogoAdidas = new javax.swing.JLabel();
        btnAdidas = new javax.swing.JButton();
        lblLogoPuma = new javax.swing.JLabel();
        btnPuma = new javax.swing.JButton();
        lblInfoNike = new javax.swing.JLabel();
        lblInfoPuma = new javax.swing.JLabel();
        lblInfoAdidas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnJordan = new javax.swing.JButton();
        lblJordanNombre = new javax.swing.JLabel();
        lblJordanPrecio = new javax.swing.JLabel();
        ckJordan1 = new javax.swing.JCheckBox();
        btnAirMax90 = new javax.swing.JButton();
        lblAirMaxNombre = new javax.swing.JLabel();
        lblAirMaxPrecio = new javax.swing.JLabel();
        ckAirMax = new javax.swing.JCheckBox();
        btnNikeDunk = new javax.swing.JButton();
        lblDunkNombre = new javax.swing.JLabel();
        lblDunkPrecio = new javax.swing.JLabel();
        ckDunk = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnPumaXRay = new javax.swing.JButton();
        lblXRayNombre = new javax.swing.JLabel();
        lblXRayPrecio = new javax.swing.JLabel();
        ckPumaXRay = new javax.swing.JCheckBox();
        btnPumaSlipstream = new javax.swing.JButton();
        lblXRayNombre1 = new javax.swing.JLabel();
        lblSlipstream = new javax.swing.JLabel();
        ckPumaSlipstream = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnYeezy = new javax.swing.JButton();
        lblYeezyNombre = new javax.swing.JLabel();
        lblYeezyPrecio = new javax.swing.JLabel();
        ckYeezy = new javax.swing.JCheckBox();
        btnForumLow = new javax.swing.JButton();
        lblForumNombre = new javax.swing.JLabel();
        lblForumPrecio = new javax.swing.JLabel();
        ckForum = new javax.swing.JCheckBox();
        btnBoost350 = new javax.swing.JButton();
        lblBoostNombre = new javax.swing.JLabel();
        lblBoostPrecio = new javax.swing.JLabel();
        ckBoost350 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCantidadProductos = new javax.swing.JTextField();
        txtPrecioSinIva = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductosSeleccionados = new javax.swing.JTable();
        txtIva = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnOpenPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TPpestanas.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnNike.setBackground(new java.awt.Color(255, 255, 255));
        btnNike.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNike.setForeground(new java.awt.Color(0, 0, 0));
        btnNike.setText("Nike");
        btnNike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNikeActionPerformed(evt);
            }
        });

        lblLogoNike.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoNike.setForeground(new java.awt.Color(255, 255, 255));

        lblLogoAdidas.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoAdidas.setForeground(new java.awt.Color(255, 255, 255));

        btnAdidas.setBackground(new java.awt.Color(255, 255, 255));
        btnAdidas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdidas.setForeground(new java.awt.Color(0, 0, 0));
        btnAdidas.setText("Adidas");
        btnAdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdidasActionPerformed(evt);
            }
        });

        lblLogoPuma.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoPuma.setForeground(new java.awt.Color(255, 255, 255));

        btnPuma.setBackground(new java.awt.Color(255, 255, 255));
        btnPuma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPuma.setForeground(new java.awt.Color(0, 0, 0));
        btnPuma.setText("Puma");
        btnPuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPumaActionPerformed(evt);
            }
        });

        lblInfoNike.setBackground(new java.awt.Color(255, 255, 255));
        lblInfoNike.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblInfoNike.setForeground(new java.awt.Color(0, 0, 0));
        lblInfoNike.setText("jLabel1");

        lblInfoPuma.setBackground(new java.awt.Color(255, 255, 255));
        lblInfoPuma.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblInfoPuma.setForeground(new java.awt.Color(0, 0, 0));
        lblInfoPuma.setText("jLabel1");

        lblInfoAdidas.setBackground(new java.awt.Color(255, 255, 255));
        lblInfoAdidas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblInfoAdidas.setForeground(new java.awt.Color(0, 0, 0));
        lblInfoAdidas.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblLogoNike, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoNike, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnNike))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblLogoAdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoAdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAdidas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblLogoPuma, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoPuma, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnPuma)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoNike, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoNike, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(btnNike)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInfoAdidas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblLogoAdidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(btnAdidas)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoPuma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoPuma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(btnPuma))
        );

        TPpestanas.addTab("Marcas", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(btnJordan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 181, 128));

        lblJordanNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblJordanNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblJordanNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblJordanNombre.setText("Jordan 1 x Off-White Chicago");
        jPanel2.add(lblJordanNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        lblJordanPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblJordanPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblJordanPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblJordanPrecio.setText("$ 109,491,323");
        jPanel2.add(lblJordanPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        ckJordan1.setBackground(new java.awt.Color(102, 102, 102));
        ckJordan1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckJordan1.setForeground(new java.awt.Color(0, 0, 0));
        ckJordan1.setText("Agregar al Carrito");
        ckJordan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckJordan1ActionPerformed(evt);
            }
        });
        jPanel2.add(ckJordan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        jPanel2.add(btnAirMax90, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 181, 128));

        lblAirMaxNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblAirMaxNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblAirMaxNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblAirMaxNombre.setText("Nike Airmax 90 x Off-White ");
        jPanel2.add(lblAirMaxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        lblAirMaxPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblAirMaxPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblAirMaxPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblAirMaxPrecio.setText("$ 13,186,660");
        jPanel2.add(lblAirMaxPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        ckAirMax.setBackground(new java.awt.Color(102, 102, 102));
        ckAirMax.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckAirMax.setForeground(new java.awt.Color(0, 0, 0));
        ckAirMax.setText("Agregar al Carrito");
        ckAirMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAirMaxActionPerformed(evt);
            }
        });
        jPanel2.add(ckAirMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));
        jPanel2.add(btnNikeDunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 181, 128));

        lblDunkNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblDunkNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDunkNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblDunkNombre.setText("Nike Dunk x Off-White ");
        jPanel2.add(lblDunkNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        lblDunkPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblDunkPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDunkPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblDunkPrecio.setText("$ 6,022,430");
        jPanel2.add(lblDunkPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        ckDunk.setBackground(new java.awt.Color(102, 102, 102));
        ckDunk.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckDunk.setForeground(new java.awt.Color(0, 0, 0));
        ckDunk.setText("Agregar al Carrito");
        ckDunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDunkActionPerformed(evt);
            }
        });
        jPanel2.add(ckDunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        TPpestanas.addTab("Nike", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblXRayNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblXRayNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblXRayNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblXRayNombre.setText("Puma X-Ray BMW Edition");

        lblXRayPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblXRayPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblXRayPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblXRayPrecio.setText("$ 520,000");

        ckPumaXRay.setBackground(new java.awt.Color(102, 102, 102));
        ckPumaXRay.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckPumaXRay.setForeground(new java.awt.Color(0, 0, 0));
        ckPumaXRay.setText("Agregar al Carrito");
        ckPumaXRay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPumaXRayActionPerformed(evt);
            }
        });

        lblXRayNombre1.setBackground(new java.awt.Color(153, 153, 153));
        lblXRayNombre1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblXRayNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lblXRayNombre1.setText("Puma Slipstream");

        lblSlipstream.setBackground(new java.awt.Color(102, 102, 102));
        lblSlipstream.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSlipstream.setForeground(new java.awt.Color(0, 0, 0));
        lblSlipstream.setText("$ 720,000");

        ckPumaSlipstream.setBackground(new java.awt.Color(102, 102, 102));
        ckPumaSlipstream.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckPumaSlipstream.setForeground(new java.awt.Color(0, 0, 0));
        ckPumaSlipstream.setText("Agregar al Carrito");
        ckPumaSlipstream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPumaSlipstreamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnPumaXRay, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblXRayNombre)
                    .addComponent(lblXRayPrecio)
                    .addComponent(ckPumaXRay)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnPumaSlipstream, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblXRayNombre1)
                    .addComponent(lblSlipstream)
                    .addComponent(ckPumaSlipstream)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPumaXRay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblXRayNombre)
                        .addGap(19, 19, 19)
                        .addComponent(lblXRayPrecio)
                        .addGap(19, 19, 19)
                        .addComponent(ckPumaXRay)))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPumaSlipstream, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblXRayNombre1)
                        .addGap(19, 19, 19)
                        .addComponent(lblSlipstream)
                        .addGap(19, 19, 19)
                        .addComponent(ckPumaSlipstream))))
        );

        TPpestanas.addTab("Puma", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblYeezyNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblYeezyNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblYeezyNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblYeezyNombre.setText("Yeezy 500 Black");

        lblYeezyPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblYeezyPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblYeezyPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblYeezyPrecio.setText("$ 1,428,960");

        ckYeezy.setBackground(new java.awt.Color(102, 102, 102));
        ckYeezy.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckYeezy.setForeground(new java.awt.Color(0, 0, 0));
        ckYeezy.setText("Agregar al Carrito");
        ckYeezy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckYeezyActionPerformed(evt);
            }
        });

        btnForumLow.setBackground(new java.awt.Color(255, 255, 255));

        lblForumNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblForumNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblForumNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblForumNombre.setText("Forum Low - Triple White");

        lblForumPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblForumPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblForumPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblForumPrecio.setText("$ 470,000");

        ckForum.setBackground(new java.awt.Color(102, 102, 102));
        ckForum.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckForum.setForeground(new java.awt.Color(0, 0, 0));
        ckForum.setText("Agregar al Carrito");
        ckForum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckForumActionPerformed(evt);
            }
        });

        lblBoostNombre.setBackground(new java.awt.Color(153, 153, 153));
        lblBoostNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBoostNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblBoostNombre.setText("Adidas Boost 350");

        lblBoostPrecio.setBackground(new java.awt.Color(102, 102, 102));
        lblBoostPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBoostPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblBoostPrecio.setText("$ 800,000");

        ckBoost350.setBackground(new java.awt.Color(102, 102, 102));
        ckBoost350.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ckBoost350.setForeground(new java.awt.Color(0, 0, 0));
        ckBoost350.setText("Agregar al Carrito");
        ckBoost350.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBoost350ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBoost350, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBoostNombre)
                            .addComponent(lblBoostPrecio)
                            .addComponent(ckBoost350)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnForumLow, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForumNombre)
                            .addComponent(lblForumPrecio)
                            .addComponent(ckForum)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnYeezy, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYeezyNombre)
                            .addComponent(lblYeezyPrecio)
                            .addComponent(ckYeezy))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnYeezy, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblYeezyNombre)
                        .addGap(19, 19, 19)
                        .addComponent(lblYeezyPrecio)
                        .addGap(19, 19, 19)
                        .addComponent(ckYeezy)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblForumNombre)
                        .addGap(19, 19, 19)
                        .addComponent(lblForumPrecio)
                        .addGap(19, 19, 19)
                        .addComponent(ckForum))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnForumLow, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBoost350, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblBoostNombre)
                        .addGap(19, 19, 19)
                        .addComponent(lblBoostPrecio)
                        .addGap(19, 19, 19)
                        .addComponent(ckBoost350)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        TPpestanas.addTab("Adidas", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Carrito de Compras");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 26, 251, 46));

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtTotalPagar.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPagar.setText("$0");
        jPanel6.add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 180, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Precio envio:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 160, -1));

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cantidad de productos:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 95, 251, -1));

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Productos seleccionados:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 251, -1));

        jLabel14.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Total a pagar:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 160, -1));

        txtCantidadProductos.setEditable(false);
        txtCantidadProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtCantidadProductos.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidadProductos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidadProductos.setText("0");
        jPanel6.add(txtCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 84, -1));

        txtPrecioSinIva.setEditable(false);
        txtPrecioSinIva.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtPrecioSinIva.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecioSinIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioSinIva.setText("$0");
        jPanel6.add(txtPrecioSinIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 180, -1));

        tblProductosSeleccionados.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tblProductosSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductosSeleccionados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblProductosSeleccionados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tblProductosSeleccionados);
        if (tblProductosSeleccionados.getColumnModel().getColumnCount() > 0) {
            tblProductosSeleccionados.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblProductosSeleccionados.getColumnModel().getColumn(1).setPreferredWidth(260);
            tblProductosSeleccionados.getColumnModel().getColumn(2).setResizable(false);
            tblProductosSeleccionados.getColumnModel().getColumn(2).setPreferredWidth(135);
        }

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 470, 140));

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtIva.setForeground(new java.awt.Color(0, 0, 0));
        txtIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIva.setText("$0");
        jPanel6.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 180, -1));

        jLabel15.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("IVA:");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 160, -1));

        btnOpenPagar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnOpenPagar.setText("PAGAR");
        jPanel6.add(btnOpenPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TPpestanas.addTab("Carrito de compras", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPpestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPpestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckBoost350ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBoost350ActionPerformed
        // TODO add your handling code here:
        Producto Boost350 = new Producto("Adidas", lblBoostNombre.getText(),
            lblBoostPrecio.getText(), Long.parseLong("" + 800000));

        CantidadProducSeleccionados(ckBoost350, Boost350);
    }//GEN-LAST:event_ckBoost350ActionPerformed

    private void ckForumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckForumActionPerformed
        // TODO add your handling code here:
        Producto ForumLow = new Producto("Adidas", lblForumNombre.getText(),
            lblForumPrecio.getText(), Long.parseLong("" + 470000));

        CantidadProducSeleccionados(ckForum, ForumLow);
    }//GEN-LAST:event_ckForumActionPerformed

    //Action Performed de la SubVentanaAdidas
    private void ckYeezyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckYeezyActionPerformed
        // TODO add your handling code here:
        Producto Yeezy = new Producto("Adidas", lblYeezyNombre.getText(),
            lblYeezyPrecio.getText(), Long.parseLong("" + 1428960));

        CantidadProducSeleccionados(ckYeezy, Yeezy);
    }//GEN-LAST:event_ckYeezyActionPerformed

    private void ckPumaSlipstreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPumaSlipstreamActionPerformed
        // TODO add your handling code here:
        Producto Slipstream = new Producto("Puma", lblXRayNombre1.getText(),
            lblSlipstream.getText(), Long.parseLong(""+720000));

        CantidadProducSeleccionados(ckPumaSlipstream, Slipstream);
    }//GEN-LAST:event_ckPumaSlipstreamActionPerformed

    //Action Performed de la SubVentana PUMA
    private void ckPumaXRayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPumaXRayActionPerformed
        // TODO add your handling code here:
        Producto XRay = new Producto("Puma", lblXRayNombre.getText(),
            lblXRayPrecio.getText(), Long.parseLong("" + 520000));

        CantidadProducSeleccionados(ckPumaXRay, XRay);
    }//GEN-LAST:event_ckPumaXRayActionPerformed

    private void ckDunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDunkActionPerformed
        // TODO add your handling code here:
        Producto Dunk = new Producto("Nike", lblDunkNombre.getText(),
            lblDunkPrecio.getText(), Long.parseLong("" + 6022430));

        CantidadProducSeleccionados(ckDunk, Dunk);
    }//GEN-LAST:event_ckDunkActionPerformed

    private void ckAirMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAirMaxActionPerformed
        // TODO add your handling code here:
        Producto AirMax = new Producto("Nike", lblAirMaxNombre.getText(),
            lblAirMaxPrecio.getText(), Long.parseLong("" + 13186660));

        CantidadProducSeleccionados(ckAirMax, AirMax);
    }//GEN-LAST:event_ckAirMaxActionPerformed

    private void ckJordan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckJordan1ActionPerformed

    }//GEN-LAST:event_ckJordan1ActionPerformed

    private void btnPumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPumaActionPerformed
        // TODO add your handling code here:
        TPpestanas.setSelectedIndex(2);
    }//GEN-LAST:event_btnPumaActionPerformed

    private void btnAdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdidasActionPerformed
        // TODO add your handling code here:
        TPpestanas.setSelectedIndex(3);
    }//GEN-LAST:event_btnAdidasActionPerformed

    private void btnNikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNikeActionPerformed
        // TODO add your handling code here:
        TPpestanas.setSelectedIndex(1);
    }//GEN-LAST:event_btnNikeActionPerformed

       
    //Funcion para mensajes en la tabla
    private void CantidadProducSeleccionados(JCheckBox botonCheck, Producto producto) {
        TotalPagar(botonCheck, producto.getValor());
        
        gestionProductos.CantidadProductosSeleccionados(botonCheck,
                tblProductosSeleccionados, txtCantidadProductos, producto);
        /* Aca invocamos a la clase GestionProductos que instanciamos al inicio de este JFrame
        y le enviamos los correspondientes valores */
    }/*Esta función es para enviar a la ventana Carrito de Compras valores, a la tabla principalmente*/

    //Funcion para enviar el precio al txtTotalPagar y el precio de todos los productos con iva al txtIva
    private void TotalPagar(JCheckBox boton, Long valor) {
        gestionProductos.TotalPagar(boton,txtPrecioSinIva,txtTotalPagar,txtIva,valor);
    }

    
    
 /*---------------------------------------------------------------------------------------------------------------------------------------------------*/
 /*---------------------------------------------------------------------------------------------------------------------------------------------------*/
    //FUNCIONES DE CONFIGURACIÓN IMAGENES Y OTRAS COSAS
    //Funcion para ajustar la imagen al tamaño del Boton
    private Icon AjustarImagen(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();

        ImageIcon imagenAjustada = new ImageIcon(icon.getImage()
                .getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return imagenAjustada;
    }

    //Funcion para ajustar la imagen al tamaño del Label
    private Icon AjustarImagen(String url, JLabel label) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = label.getWidth();
        int alto = label.getHeight();

        ImageIcon imagenAjustada = new ImageIcon(icon.getImage()
                .getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return imagenAjustada;
    }

    //Funcion para enviar mensaje al label
    private void MensajeLabel() {
        lblInfoNike.setText("<html>Nike Inc.es una empresa multinacional estadounidense"
                + "dedicada al diseño, desarrollo, fabricación y comercialización de "
                + "equipamiento deportivo: balones, calzado, ropa, equipo, accesorios "
                + "y otros artículos deportivos.</html>");

        lblInfoAdidas.setText("<html>Adidas es una empresa alemana fundada en 1949 por"
                + "Adolf Dassler, especializada en la fabricación de artículos deportivos,"
                + "con sede en Herzogenaurach (Alemania). Su facturación global fue de"
                + "23.600 millones de euros en 2019. Emplea a 56.000 personas.</html>");

        lblInfoPuma.setText("<html>PUMA es el tercer fabricante de ropa deportiva más grande "
                + "del mundo, ofrece productos para el fútbol, para correr, para el "
                + "entrenamiento físico, el golf, los deportes de motor y estilo de vida.</html>");
    }

    //Funcion para enviar imagenes a todos los componentes
    private void ImagenesComponentes() {
        lblLogoNike.setIcon(AjustarImagen("/imagenes/LogoNike.png", lblLogoNike));
        lblLogoAdidas.setIcon(AjustarImagen("/imagenes/LogoAdidas.png", lblLogoAdidas));
        lblLogoPuma.setIcon(AjustarImagen("/imagenes/LogoPuma.png", lblLogoPuma));
        //Ventana Nike
        btnJordan.setIcon(AjustarImagen("/imagenes/Jordan1xOffWhite.jpg", btnJordan));
        btnAirMax90.setIcon(AjustarImagen("/imagenes/airmax90xOffWhite.png", btnAirMax90));
        btnNikeDunk.setIcon(AjustarImagen("/imagenes/DunkxOffWhite.jpg", btnNikeDunk));
        //Ventana Adidas
        btnYeezy.setIcon(AjustarImagen("/imagenes/Yeezy500.jpg", btnYeezy));
        btnForumLow.setIcon(AjustarImagen("/imagenes/ForumLow.jpg", btnForumLow));
        btnBoost350.setIcon(AjustarImagen("/imagenes/Boost350.jpg", btnBoost350));
        //Ventana Puma
        btnPumaXRay.setIcon(AjustarImagen("/imagenes/PumaXRay.jpg", btnPumaXRay));
        btnPumaSlipstream.setIcon(AjustarImagen("/imagenes/PumaSlipstream.jfif", btnPumaSlipstream));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaZapatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaZapatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaZapatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaZapatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaZapatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TPpestanas;
    private javax.swing.JButton btnAdidas;
    private javax.swing.JButton btnAirMax90;
    private javax.swing.JButton btnBoost350;
    private javax.swing.JButton btnForumLow;
    private javax.swing.JButton btnJordan;
    private javax.swing.JButton btnNike;
    private javax.swing.JButton btnNikeDunk;
    private javax.swing.JButton btnOpenPagar;
    private javax.swing.JButton btnPuma;
    private javax.swing.JButton btnPumaSlipstream;
    private javax.swing.JButton btnPumaXRay;
    private javax.swing.JButton btnYeezy;
    private javax.swing.JCheckBox ckAirMax;
    private javax.swing.JCheckBox ckBoost350;
    private javax.swing.JCheckBox ckDunk;
    private javax.swing.JCheckBox ckForum;
    private javax.swing.JCheckBox ckJordan1;
    private javax.swing.JCheckBox ckPumaSlipstream;
    private javax.swing.JCheckBox ckPumaXRay;
    private javax.swing.JCheckBox ckYeezy;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAirMaxNombre;
    private javax.swing.JLabel lblAirMaxPrecio;
    private javax.swing.JLabel lblBoostNombre;
    private javax.swing.JLabel lblBoostPrecio;
    private javax.swing.JLabel lblDunkNombre;
    private javax.swing.JLabel lblDunkPrecio;
    private javax.swing.JLabel lblForumNombre;
    private javax.swing.JLabel lblForumPrecio;
    private javax.swing.JLabel lblInfoAdidas;
    private javax.swing.JLabel lblInfoNike;
    private javax.swing.JLabel lblInfoPuma;
    private javax.swing.JLabel lblJordanNombre;
    private javax.swing.JLabel lblJordanPrecio;
    private javax.swing.JLabel lblLogoAdidas;
    private javax.swing.JLabel lblLogoNike;
    private javax.swing.JLabel lblLogoPuma;
    private javax.swing.JLabel lblSlipstream;
    private javax.swing.JLabel lblXRayNombre;
    private javax.swing.JLabel lblXRayNombre1;
    private javax.swing.JLabel lblXRayPrecio;
    private javax.swing.JLabel lblYeezyNombre;
    private javax.swing.JLabel lblYeezyPrecio;
    private javax.swing.JTable tblProductosSeleccionados;
    private javax.swing.JTextField txtCantidadProductos;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtPrecioSinIva;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
